### ISSUE TITLE
DNS over HTTPS resolution doesn't happen on Windows

### ISSUE THREAD

**Issue by bulanula** [emilliken/doh5#2]
Hi, 

First of all let me say that this is a unique project as I haven't seen anything like this before out in the wild; thank you for all your work on this and for making it public, really appreciate that. 

I've tried this out on Linux and the SOCKS5 portion as well as the DNS over HTTPS portion works very well and is much more reliable than other similar projects I've seen. 

However, on Windows, while the SOCKS5 portion works well, the system resolver takes precedence over DNS over HTTPS. I've tested this by using "curl --socks5-hostname 127.0.0.1:1080 https://blocked.com".

I've read that the Go DNS behavior will vary depending on the runtime OS but I'm hoping that either I've made a mistake or we can find a way to make the DoH resolution also work while on Windows.

Please let me know if you need any more details.

Many thanks !

**Comment by mllken** [comment]
Looks like you're encountering https://github.com/golang/go/issues/33621

**Comment by mllken** [comment]
Fixed in Go 1.19 via https://github.com/golang/go/issues/33097.  Closing.
