### ISSUE TITLE
unknown field 'MaxConnsPerHost' in struct literal of type http.Transport

### ISSUE THREAD

**Issue by specterz** [emilliken/doh5#3]
When I run the "go get" command, I receive an error:

root@proxy-test2:/tmp/doh5# go get github.com/emilliken/doh5
# github.com/emilliken/doh5
/root/go/src/github.com/emilliken/doh5/resolver.go:64:19: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport

**Comment by mllken** [comment]
Which version of Go are you using?  MaxConnsPerHost field was added in Go 1.11:

https://golang.org/pkg/net/http/#Transport.MaxConnsPerHost

I should probably document this...

**Comment by mllken** [comment]
I've now documented this in the README in commit https://github.com/emilliken/doh5/commit/21c3f06fd3c967bad2eb4f8ec9b6eb9c94667255
